### ISSUE TITLE
Swagger Error - Ambiguous HTTP method for action

### ISSUE THREAD

**Issue by mclausing** [tomahg/Gulla.Episerver.SqlStudio#4]
We're unable to access our Swagger page for a client, and are seeing the following exception:

```
An unhandled exception has occurred while executing the request.
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - Gulla.Episerver.SqlStudio.Controllers.AdminController.Index (Gulla.Episerver.SqlStudio). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

I'm working on a work around for it to keep them up and running, but wanted to bring it to your attention.

**Comment by tomahg** [comment]
Hi @mclausing, are you using the CMS 11 or CMS 12 version?

Would it solve your problem if I add this to the actions?
`[ApiExplorerSettings(IgnoreApi = true)]`

**Comment by mclausing** [comment]
This is for CMS 12, version 2.9.2 of the SqlStudio package. 

I'm not positive on the fix. I'm looking to ignore it in a DocumentFilter during startup.
